In [2]:
import numpy as np
from numpy import genfromtxt

In [21]:
np_2d = np.array([[5,6,1,2,3,4,3],[4,5,3,2,1,8,3],[9,10,3,7,6,5,3],[1,2,3,4,5,6,7]])  
print(np_2d)

[[ 5  6  1  2  3  4  3]
 [ 4  5  3  2  1  8  3]
 [ 9 10  3  7  6  5  3]
 [ 1  2  3  4  5  6  7]]


In [39]:
print(np_2d[:,5]) # slicing --> [all lines]][column 5]
print(np_2d[1:,4]) # [starts on 1 to the end][column 4]

[4 8 5 6]
[1 6 5]
[3 4 5 6 7]


#### How selects by horizontal line:

In [51]:
print(np_2d[3,2:]) # [stars on 3º line and 2º column to the end of line]
print(np_2d[2,1:])

[3 4 5 6 7]
[10  3  7  6  5  3]


#### How selects by vertical line:

In [49]:
print(np_2d[:3,4]) # begins on 4º column and starts from 0 to 3 exclusive index
print(np_2d[:4,5])

[3 1 6]
[4 8 5 6]
